import React, { useEffect, useMemo, useState } from 'react';
import { createPortal } from 'react-dom';
import { useCreateMandatMutation, useCreateAvenantMutation, useGetMeQuery } from '../api/baseApi';

/**
 * ManualDocsWizard
 * Props:
 *  - open: boolean
 *  - onClose: () => void
 *  - proprietaires: array of owners available for selection
 *  - defaultProprietaireId: number | undefined
 *  - defaultDateDebut: string (yyyy-mm-dd, prefilled from UniteOwners)
 *  - defaultDateFin: string (yyyy-mm-dd, prefilled from UniteOwners)
 *  - uniteDescription: string (optional prefilled description)
 *  - allowAvenant: boolean (if user wants to optionally create avenant right after mandat)
 *  - lockCoreFields: boolean (if true, proprietaire and dates are prefilled and disabled)
 */
export default function ManualDocsWizard({ open, onClose, proprietaires, defaultProprietaireId, defaultDateDebut, defaultDateFin, uniteDescription, allowAvenant, lockCoreFields = false }) {
  const { data: me } = useGetMeQuery();
  const [createMandat, { isLoading: isSavingMandat }] = useCreateMandatMutation();
  const [createAvenant, { isLoading: isSavingAvenant }] = useCreateAvenantMutation();
  // step: 0 select mode, 1 mandat form, 2 avenant form, 3 done
  const [step, setStep] = useState(0);
  const [mode, setMode] = useState('both'); // 'mandat' | 'avenant' | 'both'
  const [mandat, setMandat] = useState({
    proprietaire_id: defaultProprietaireId || '',
    date_debut: defaultDateDebut || '',
    date_fin: defaultDateFin || '',
    assiette_honoraires: 'loyers_encaisse',
    taux_gestion_pct: '',
    tva_applicable: false,
    tva_taux: '',
    frais_min_mensuel: '',
    periodicite_releve: 'mensuel',
    charge_maintenance: 'proprietaire',
    mode_versement: 'virement',
    description_bien: uniteDescription || '',
    usage_bien: 'habitation',
    pouvoirs_accordes: '',
    lieu_signature: '',
    date_signature: '',
    langue: 'fr',
    notes_clauses: '',
    statut: 'brouillon',
  });

  const [avenant, setAvenant] = useState({
    mandat_id: null,
    reference: '',
    date_pouvoir_initial: '',
    objet_resume: '',
    modifs_text: '',
    date_effet: '',
    lieu_signature: '',
    date_signature: '',
    rep_b_user_id: undefined,
    fichier_url: '',
    created_by: undefined,
    statut: 'brouillon'
  });

  const [errors, setErrors] = useState({});
  const [avenantErrors, setAvenantErrors] = useState({});
  const [createdMandat, setCreatedMandat] = useState(null);
  const [createdAvenant, setCreatedAvenant] = useState(null);

  useEffect(() => {
    if (me?.id) {
      setAvenant(a => ({ ...a, rep_b_user_id: me.id, created_by: me.id }));
    }
  }, [me]);

  // Keep mandat core fields in sync with owner flow and lock them
  useEffect(() => {
    setMandat(m => ({
      ...m,
      proprietaire_id: defaultProprietaireId || m.proprietaire_id,
      date_debut: defaultDateDebut || m.date_debut,
      date_fin: defaultDateFin || m.date_fin,
    }));
  }, [defaultProprietaireId, defaultDateDebut, defaultDateFin]);

  if (!open) return null;

  const validateMandat = () => {
    const e = {};
    if (!mandat.proprietaire_id) e.proprietaire_id = 'Choisir un propriétaire';
    if (!mandat.date_debut) e.date_debut = 'Date début requise';
    if (mandat.date_fin && mandat.date_fin < mandat.date_debut) e.date_fin = 'Date fin doit être >= date début';
    return e;
  };

  const validateAvenant = () => {
    const e = {};
    if (!avenant.mandat_id) e.mandat_id = 'Mandat requis';
    if (!avenant.date_effet) e.date_effet = 'Date effet requise';
    if (!avenant.rep_b_user_id) e.rep_b_user_id = 'Signataire interne requis';
    return e;
  };

  const saveMandat = async () => {
    const e = validateMandat();
    setErrors(e);
    if (Object.keys(e).length) return;
    try {
      const payload = {
        ...mandat,
        proprietaire_id: Number(mandat.proprietaire_id),
        taux_gestion_pct: mandat.taux_gestion_pct ? Number(mandat.taux_gestion_pct) : null,
        tva_taux: mandat.tva_taux ? Number(mandat.tva_taux) : null,
        frais_min_mensuel: mandat.frais_min_mensuel ? Number(mandat.frais_min_mensuel) : null,
      };
      // Ensure reference is autogenerated by backend: do not send empty reference
      delete payload.reference;
      const res = await createMandat(payload).unwrap();
      setCreatedMandat(res);
      setAvenant(a => ({ ...a, mandat_id: res.id }));
      if (mode === 'both' && allowAvenant) setStep(2);
      else setStep(3);
    } catch (err) {
      console.error(err);
      alert('Erreur création mandat: ' + (err?.data?.message || err?.message || 'Serveur'));
    }
  };

  const saveAvenant = async () => {
    const e = validateAvenant();
    setAvenantErrors(e);
    if (Object.keys(e).length) return;
    try {
      let payload = {
        ...avenant,
        mandat_id: Number(avenant.mandat_id),
        rep_b_user_id: Number(avenant.rep_b_user_id),
        created_by: avenant.created_by ? Number(avenant.created_by) : undefined
      };
      if (avenant.file) {
        payload.file = avenant.file;
      }
      const res = await createAvenant(payload).unwrap();
      setCreatedAvenant(res);
      setStep(3);
    } catch (err) {
      console.error(err);
      alert('Erreur création avenant: ' + (err?.data?.message || err?.message || 'Serveur'));
    }
  };

  const closeAndReset = () => {
    setStep(0);
    setMode('both');
    setCreatedMandat(null);
    setCreatedAvenant(null);
    setErrors({});
    setAvenantErrors({});
    onClose();
  };

  const chooseStep = (
    <div className="p-4">
      <div className="text-center mb-4">
        <div className="d-inline-flex align-items-center justify-content-center bg-primary bg-opacity-10 rounded-circle p-3 mb-3">
          <i className="bi bi-file-earmark-plus fs-1 text-primary"></i>
        </div>
        <h5 className="fw-bold mb-2">Créer des documents</h5>
        <p className="text-muted mb-0">Choisissez le type de document à générer</p>
      </div>
      <div className="d-flex flex-column gap-3">
        <div className={`card border-2 ${mode === 'mandat' ? 'border-primary shadow-sm' : 'border'}`} style={{ cursor: 'pointer' }} onClick={() => setMode('mandat')}>
          <div className="card-body d-flex align-items-center gap-3 py-3">
            <input type="radio" className="form-check-input fs-5" name="mode" checked={mode === 'mandat'} onChange={() => setMode('mandat')} />
            <div className="flex-grow-1">
              <div className="fw-semibold d-flex align-items-center gap-2">
                <i className="bi bi-file-text text-primary"></i>
                Mandat de gestion uniquement
              </div>
              <small className="text-muted">Créer un nouveau mandat de gestion</small>
            </div>
          </div>
        </div>
        <div className={`card border-2 ${mode === 'avenant' ? 'border-primary shadow-sm' : 'border'}`} style={{ cursor: 'pointer' }} onClick={() => setMode('avenant')}>
          <div className="card-body d-flex align-items-center gap-3 py-3">
            <input type="radio" className="form-check-input fs-5" name="mode" checked={mode === 'avenant'} onChange={() => setMode('avenant')} />
            <div className="flex-grow-1">
              <div className="fw-semibold d-flex align-items-center gap-2">
                <i className="bi bi-file-earmark-plus text-warning"></i>
                Avenant uniquement
              </div>
              <small className="text-muted">Créer un avenant pour un mandat existant</small>
            </div>
          </div>
        </div>
        <div className={`card border-2 ${mode === 'both' ? 'border-primary shadow-sm' : 'border'}`} style={{ cursor: 'pointer' }} onClick={() => setMode('both')}>
          <div className="card-body d-flex align-items-center gap-3 py-3">
            <input type="radio" className="form-check-input fs-5" name="mode" checked={mode === 'both'} onChange={() => setMode('both')} />
            <div className="flex-grow-1">
              <div className="fw-semibold d-flex align-items-center gap-2">
                <i className="bi bi-files text-success"></i>
                Les deux (mandat puis avenant)
              </div>
              <small className="text-muted">Créer un mandat et son avenant associé</small>
            </div>
          </div>
        </div>
      </div>
      <div className="d-flex justify-content-end mt-4 gap-2">
        <button type="button" className="btn btn-outline-secondary px-4" onClick={closeAndReset}>
          <i className="bi bi-x-lg me-2"></i>Annuler
        </button>
        <button type="button" className="btn btn-primary px-4" onClick={() => setStep(mode === 'avenant' ? 2 : 1)}>
          Continuer<i className="bi bi-arrow-right ms-2"></i>
        </button>
      </div>
    </div>
  );

  const mandatForm = (
    <div className="p-4">
      <div className="mb-4 pb-3 border-bottom">
        <div className="d-flex align-items-center gap-2 mb-2">
          <i className="bi bi-file-text fs-4 text-primary"></i>
          <h5 className="fw-bold mb-0">Nouveau Mandat de gestion</h5>
        </div>
        <p className="text-muted mb-0 small">Remplissez les informations du mandat</p>
      </div>

      {/* Section: Informations principales */}
      <div className="mb-4">
        <h6 className="text-muted fw-semibold mb-3 d-flex align-items-center gap-2">
          <i className="bi bi-person-circle text-primary"></i>
          Propriétaire et période
        </h6>
        <div className="row g-3">
          <div className="col-md-6">
            <label className="form-label fw-medium">
              <i className="bi bi-person me-1"></i>Propriétaire <span className="text-danger">*</span>
            </label>
            <select className={`form-select ${errors.proprietaire_id ? 'is-invalid' : ''}`} value={mandat.proprietaire_id} onChange={e => setMandat(m => ({ ...m, proprietaire_id: e.target.value }))} disabled={lockCoreFields && !!mandat.proprietaire_id}>
              <option value="">Choisir...</option>
              {proprietaires.map(p => <option key={p.id} value={p.id}>{p.nom_raison || p.email || `#${p.id}`}</option>)}
            </select>
            {errors.proprietaire_id && <div className="invalid-feedback">{errors.proprietaire_id}</div>}
            {lockCoreFields && mandat.proprietaire_id && (
              <div className="form-text text-info"><i className="bi bi-lock me-1"></i>Défini par la répartition de l'unité</div>
            )}
          </div>
          <div className="col-md-3">
            <label className="form-label fw-medium">
              <i className="bi bi-calendar-check me-1"></i>Date début <span className="text-danger">*</span>
            </label>
            <input type="date" className={`form-control ${errors.date_debut ? 'is-invalid' : ''}`} value={mandat.date_debut} onChange={e => setMandat(m => ({ ...m, date_debut: e.target.value }))} disabled={lockCoreFields} />
            {errors.date_debut && <div className="invalid-feedback">{errors.date_debut}</div>}
            {lockCoreFields && <div className="form-text text-info"><i className="bi bi-lock me-1"></i>Défini automatiquement</div>}
          </div>
          <div className="col-md-3">
            <label className="form-label fw-medium">
              <i className="bi bi-calendar-x me-1"></i>Date fin
            </label>
            <input type="date" className={`form-control ${errors.date_fin ? 'is-invalid' : ''}`} value={mandat.date_fin} onChange={e => setMandat(m => ({ ...m, date_fin: e.target.value }))} disabled={lockCoreFields} />
            {errors.date_fin && <div className="invalid-feedback">{errors.date_fin}</div>}
            {lockCoreFields && <div className="form-text text-info"><i className="bi bi-lock me-1"></i>Défini automatiquement</div>}
          </div>
        </div>
      </div>

      <hr className="my-4" />

      {/* Section: Honoraires */}
      <div className="mb-4">
        <h6 className="text-muted fw-semibold mb-3 d-flex align-items-center gap-2">
          <i className="bi bi-cash-coin text-success"></i>
          Honoraires et gestion
        </h6>
        <div className="row g-3">
          <div className="col-md-4">
            <label className="form-label fw-medium">
              <i className="bi bi-percent me-1"></i>Taux gestion (%)
            </label>
            <div className="input-group">
              <input type="number" step="0.01" className="form-control" value={mandat.taux_gestion_pct} onChange={e => setMandat(m => ({ ...m, taux_gestion_pct: e.target.value }))} placeholder="0.00" />
              <span className="input-group-text">%</span>
            </div>
          </div>
          <div className="col-md-4">
            <label className="form-label fw-medium">
              <i className="bi bi-translate me-1"></i>Langue
            </label>
            <select className="form-select" value={mandat.langue} onChange={e => setMandat(m => ({ ...m, langue: e.target.value }))}>
              <option value="fr">🇫🇷 Français</option>
              <option value="ar">🇲🇦 Arabe</option>
              <option value="ar_fr">🇲🇦🇫🇷 Ar + Fr</option>
            </select>
          </div>
          <div className="col-md-4">
            <label className="form-label fw-medium">
              <i className="bi bi-tag me-1"></i>Statut
            </label>
            <select className="form-select" value={mandat.statut} onChange={e => setMandat(m => ({ ...m, statut: e.target.value }))}>
              <option value="brouillon">📝 Brouillon</option>
              <option value="en_validation">⏳ En validation</option>
              <option value="signe">✅ Signé</option>
              <option value="actif">🟢 Actif</option>
              <option value="resilie">🔴 Résilié</option>
            </select>
          </div>
        </div>
      </div>

      <hr className="my-4" />

      {/* Section: Description */}
      <div className="mb-4">
        <h6 className="text-muted fw-semibold mb-3 d-flex align-items-center gap-2">
          <i className="bi bi-file-earmark-text text-info"></i>
          Description et clauses
        </h6>
        <div className="row g-3">
          <div className="col-12">
            <label className="form-label fw-medium">
              <i className="bi bi-building me-1"></i>Description du bien
            </label>
            <textarea className="form-control" rows={2} value={mandat.description_bien} onChange={e => setMandat(m => ({ ...m, description_bien: e.target.value }))} placeholder="Décrire le bien..." />
          </div>
          <div className="col-12">
            <label className="form-label fw-medium">
              <i className="bi bi-list-check me-1"></i>Pouvoirs accordés / Texte
            </label>
            <textarea className="form-control" rows={3} value={mandat.pouvoirs_accordes} onChange={e => setMandat(m => ({ ...m, pouvoirs_accordes: e.target.value }))} placeholder="Détailler les pouvoirs..." />
          </div>
          <div className="col-12">
            <label className="form-label fw-medium">
              <i className="bi bi-journal-text me-1"></i>Clauses / Notes
            </label>
            <textarea className="form-control" rows={2} value={mandat.notes_clauses} onChange={e => setMandat(m => ({ ...m, notes_clauses: e.target.value }))} placeholder="Notes additionnelles..." />
          </div>
        </div>
      </div>

      <hr className="my-4" />

      {/* Section: Signature */}
      <div className="mb-4">
        <h6 className="text-muted fw-semibold mb-3 d-flex align-items-center gap-2">
          <i className="bi bi-pen text-secondary"></i>
          Signature
        </h6>
        <div className="row g-3">
          <div className="col-md-4">
            <label className="form-label fw-medium">
              <i className="bi bi-calendar-event me-1"></i>Date signature
            </label>
            <input type="date" className="form-control" value={mandat.date_signature} onChange={e => setMandat(m => ({ ...m, date_signature: e.target.value }))} />
          </div>
          <div className="col-md-4">
            <label className="form-label fw-medium">
              <i className="bi bi-geo-alt me-1"></i>Lieu signature
            </label>
            <input type="text" className="form-control" value={mandat.lieu_signature} onChange={e => setMandat(m => ({ ...m, lieu_signature: e.target.value }))} placeholder="Ville ou lieu..." />
          </div>
          <div className="col-md-4">
            <label className="form-label fw-medium">
              <i className="bi bi-file-earmark-pdf me-1"></i>Fichier URL
            </label>
            <input type="text" className="form-control" value={mandat.fichier_url} onChange={e => setMandat(m => ({ ...m, fichier_url: e.target.value }))} placeholder="https://..." />
          </div>
        </div>
      </div>

      <div className="d-flex justify-content-between mt-4 pt-3 border-top gap-2">
        <button type="button" className="btn btn-outline-secondary px-4" disabled={isSavingMandat} onClick={closeAndReset}>
          <i className="bi bi-x-lg me-2"></i>Annuler
        </button>
        <button type="button" className="btn btn-primary px-4" disabled={isSavingMandat} onClick={saveMandat}>
          {isSavingMandat ? (
            <>
              <span className="spinner-border spinner-border-sm me-2"></span>
              Création...
            </>
          ) : (
            <>
              <i className="bi bi-check-lg me-2"></i>Créer le mandat
            </>
          )}
        </button>
      </div>
    </div>
  );

  const avenantForm = (
    <div className="p-4">
      <div className="mb-4 pb-3 border-bottom">
        <div className="d-flex align-items-center gap-2 mb-2">
          <i className="bi bi-file-earmark-plus fs-4 text-warning"></i>
          <h5 className="fw-bold mb-0">Nouvel Avenant</h5>
        </div>
        <p className="text-muted mb-0 small">Remplissez les informations de l'avenant</p>
      </div>

      {/* Section: Identification */}
      <div className="mb-4">
        <h6 className="text-muted fw-semibold mb-3 d-flex align-items-center gap-2">
          <i className="bi bi-hash text-primary"></i>
          Identification
        </h6>
        <div className="row g-3">
          {!createdMandat && (
            <div className="col-md-4">
              <label className="form-label fw-medium">
                <i className="bi bi-link me-1"></i>ID Mandat <span className="text-danger">*</span>
              </label>
              <input type="number" className={`form-control ${avenantErrors.mandat_id ? 'is-invalid' : ''}`} value={avenant.mandat_id || ''} onChange={e => setAvenant(a => ({ ...a, mandat_id: e.target.value }))} placeholder="Ex: 123" />
              {avenantErrors.mandat_id && <div className="invalid-feedback">{avenantErrors.mandat_id}</div>}
            </div>
          )}
          <div className="col-md-4">
            <label className="form-label fw-medium">
              <i className="bi bi-file-text me-1"></i>Référence
            </label>
            <input type="text" className="form-control" value={avenant.reference} onChange={e => setAvenant(a => ({ ...a, reference: e.target.value }))} placeholder="AV-2024-..." />
          </div>
          <div className="col-md-4">
            <label className="form-label fw-medium">
              <i className="bi bi-tag me-1"></i>Statut
            </label>
            <select className="form-select" value={avenant.statut} onChange={e => setAvenant(a => ({ ...a, statut: e.target.value }))}>
              <option value="brouillon">📝 Brouillon</option>
              <option value="signe">✅ Signé</option>
              <option value="actif">🟢 Actif</option>
              <option value="annule">🔴 Annulé</option>
            </select>
          </div>
        </div>
      </div>

      <hr className="my-4" />

      {/* Section: Dates et objet */}
      <div className="mb-4">
        <h6 className="text-muted fw-semibold mb-3 d-flex align-items-center gap-2">
          <i className="bi bi-calendar-range text-success"></i>
          Dates et objet
        </h6>
        <div className="row g-3">
          <div className="col-md-4">
            <label className="form-label fw-medium">
              <i className="bi bi-calendar-check me-1"></i>Date pouvoir initial
            </label>
            <input type="date" className="form-control" value={avenant.date_pouvoir_initial || ''} onChange={e => setAvenant(a => ({ ...a, date_pouvoir_initial: e.target.value }))} />
          </div>
          <div className="col-md-4">
            <label className="form-label fw-medium">
              <i className="bi bi-calendar-event me-1"></i>Date effet <span className="text-danger">*</span>
            </label>
            <input type="date" className={`form-control ${avenantErrors.date_effet ? 'is-invalid' : ''}`} value={avenant.date_effet} onChange={e => setAvenant(a => ({ ...a, date_effet: e.target.value }))} />
            {avenantErrors.date_effet && <div className="invalid-feedback">{avenantErrors.date_effet}</div>}
          </div>
          <div className="col-md-4">
            <label className="form-label fw-medium">
              <i className="bi bi-calendar3 me-1"></i>Date de signature
            </label>
            <input type="date" className="form-control" value={avenant.date_signature || ''} onChange={e => setAvenant(a => ({ ...a, date_signature: e.target.value }))} />
          </div>
          <div className="col-12">
            <label className="form-label fw-medium">
              <i className="bi bi-card-text me-1"></i>Objet résumé
            </label>
            <input type="text" className="form-control" value={avenant.objet_resume} onChange={e => setAvenant(a => ({ ...a, objet_resume: e.target.value }))} placeholder="Résumé bref..." />
          </div>
        </div>
      </div>

      <hr className="my-4" />

      {/* Section: Modifications */}
      <div className="mb-4">
        <h6 className="text-muted fw-semibold mb-3 d-flex align-items-center gap-2">
          <i className="bi bi-pencil-square text-info"></i>
          Modifications et texte
        </h6>
        <div className="row g-3">
          <div className="col-12">
            <label className="form-label fw-medium">
              <i className="bi bi-journal-text me-1"></i>Modifications / Texte
            </label>
            <textarea className="form-control" rows={4} value={avenant.modifs_text} onChange={e => setAvenant(a => ({ ...a, modifs_text: e.target.value }))} placeholder="Détailler les modifications..." />
          </div>
        </div>
      </div>

      <hr className="my-4" />

      {/* Section: Signature et fichier */}
      <div className="mb-4">
        <h6 className="text-muted fw-semibold mb-3 d-flex align-items-center gap-2">
          <i className="bi bi-pen text-secondary"></i>
          Signature et fichier
        </h6>
        <div className="row g-3">
          <div className="col-md-4">
            <label className="form-label fw-medium">
              <i className="bi bi-geo-alt me-1"></i>Lieu de signature
            </label>
            <input type="text" className="form-control" value={avenant.lieu_signature} onChange={e => setAvenant(a => ({ ...a, lieu_signature: e.target.value }))} placeholder="Ville ou lieu..." />
          </div>
          <div className="col-md-4">
            <label className="form-label fw-medium">
              <i className="bi bi-person-badge me-1"></i>Signataire interne (ID) <span className="text-danger">*</span>
            </label>
            <input type="number" className={`form-control ${avenantErrors.rep_b_user_id ? 'is-invalid' : ''}`} value={avenant.rep_b_user_id || ''} onChange={e => setAvenant(a => ({ ...a, rep_b_user_id: e.target.value }))} placeholder="ID utilisateur" />
            {avenantErrors.rep_b_user_id && <div className="invalid-feedback">{avenantErrors.rep_b_user_id}</div>}
          </div>
          <div className="col-md-4">
            <label className="form-label fw-medium">
              <i className="bi bi-person-plus me-1"></i>Créé par (ID)
            </label>
            <input type="number" className="form-control" value={avenant.created_by || ''} onChange={e => setAvenant(a => ({ ...a, created_by: e.target.value }))} placeholder={`Par défaut: ${me?.id ?? '...'}`} />
            <div className="form-text">Par défaut: votre ID ({me?.id ?? '...'})</div>
          </div>
          <div className="col-12">
            <label className="form-label fw-medium">
              <i className="bi bi-file-earmark-arrow-up me-1"></i>Fichier (upload)
            </label>
            <input type="file" className="form-control" accept=".pdf,.jpg,.jpeg,.png" onChange={e => {
              const file = e.target.files?.[0];
              setAvenant(a => ({ ...a, file }));
            }} />
            {avenant.fichier_url && (
              <div className="alert alert-info mt-2 mb-0 py-2 d-flex align-items-center gap-2">
                <i className="bi bi-file-earmark-check"></i>
                <span>Fichier actuel: <a href={avenant.fichier_url} target="_blank" rel="noreferrer" className="alert-link">ouvrir</a></span>
              </div>
            )}
          </div>
        </div>
      </div>
      <div className="d-flex justify-content-between mt-4 pt-3 border-top gap-2">
        {mode === 'both' && (
          <button type="button" className="btn btn-outline-warning px-4" onClick={() => setStep(3)} disabled={isSavingAvenant}>
            <i className="bi bi-skip-forward me-2"></i>Ignorer l'avenant
          </button>
        )}
        <div className="ms-auto d-flex gap-2">
          {!createdMandat && (
            <button type="button" className="btn btn-outline-secondary px-4" onClick={() => setStep(1)} disabled={isSavingAvenant}>
              <i className="bi bi-arrow-left me-2"></i>Retour
            </button>
          )}
          <button type="button" className="btn btn-primary px-4" disabled={isSavingAvenant} onClick={saveAvenant}>
            {isSavingAvenant ? (
              <>
                <span className="spinner-border spinner-border-sm me-2"></span>
                Création...
              </>
            ) : (
              <>
                <i className="bi bi-check-lg me-2"></i>Créer avenant
              </>
            )}
          </button>
        </div>
      </div>
    </div>
  );

  const doneView = (
    <div className="text-center py-5">
      <div className="mb-4">
        <div className="d-inline-flex align-items-center justify-content-center bg-success bg-opacity-10 rounded-circle p-4 mb-3">
          <i className="bi bi-check-circle-fill fs-1 text-success"></i>
        </div>
        <h5 className="fw-bold mb-2">Création terminée avec succès !</h5>
        <p className="text-muted">Vos documents ont été créés</p>
      </div>
      <div className="mb-4">
        {createdMandat && (
          <div className="alert alert-success d-inline-flex align-items-center mb-2">
            <i className="bi bi-file-text me-2"></i>
            <span>Mandat #{createdMandat.id} créé</span>
          </div>
        )}
        {createdAvenant && (
          <div className="alert alert-info d-inline-flex align-items-center mb-2">
            <i className="bi bi-file-earmark-plus me-2"></i>
            <span>Avenant #{createdAvenant.id} créé</span>
          </div>
        )}
      </div>
      <div className="d-flex justify-content-center gap-2">
        <button type="button" className="btn btn-primary px-4" onClick={closeAndReset}>
          <i className="bi bi-check-lg me-2"></i>Terminer
        </button>
      </div>
    </div>
  );

  const body = (
    <div className="modal fade show" style={{ display: 'block', background: 'rgba(0,0,0,0.5)', zIndex: 1050 }}>
      <div className="modal-dialog modal-xl modal-dialog-scrollable modal-dialog-centered">
        <div className="modal-content border-0 shadow-lg" style={{ borderRadius: '1rem' }}>
          <div className="modal-header border-0 pb-0">
            <div className="w-100">
              {/* Progress indicator */}
              <div className="d-flex align-items-center justify-content-between mb-3">
                <div className="d-flex align-items-center gap-2">
                  <div className={`rounded-circle ${step >= 0 ? 'bg-primary text-white' : 'bg-light text-muted'}`} style={{ width: '32px', height: '32px', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '14px', fontWeight: 'bold' }}>
                    {step > 0 ? <i className="bi bi-check-lg"></i> : '1'}
                  </div>
                  <span className={`small ${step >= 0 ? 'fw-semibold' : 'text-muted'}`}>Type</span>
                  <div className="border-top flex-grow-1 mx-2" style={{ width: '40px' }}></div>
                  <div className={`rounded-circle ${step >= 1 ? 'bg-primary text-white' : 'bg-light text-muted'}`} style={{ width: '32px', height: '32px', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '14px', fontWeight: 'bold' }}>
                    {step > 1 ? <i className="bi bi-check-lg"></i> : '2'}
                  </div>
                  <span className={`small ${step >= 1 ? 'fw-semibold' : 'text-muted'}`}>Informations</span>
                  <div className="border-top flex-grow-1 mx-2" style={{ width: '40px' }}></div>
                  <div className={`rounded-circle ${step >= 3 ? 'bg-success text-white' : 'bg-light text-muted'}`} style={{ width: '32px', height: '32px', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '14px', fontWeight: 'bold' }}>
                    {step >= 3 ? <i className="bi bi-check-lg"></i> : '3'}
                  </div>
                  <span className={`small ${step >= 3 ? 'fw-semibold' : 'text-muted'}`}>Terminé</span>
                </div>
                <button type="button" className="btn-close" onClick={closeAndReset} />
              </div>
              <h5 className="modal-title fw-bold">
                {step === 0 && 'Assistant de création de documents'}
                {step === 1 && 'Mandat de gestion'}
                {step === 2 && 'Avenant au mandat'}
                {step === 3 && 'Finalisation'}
              </h5>
            </div>
          </div>
          <div className="modal-body p-0">
            {step === 0 && chooseStep}
            {step === 1 && mandatForm}
            {step === 2 && avenantForm}
            {step === 3 && doneView}
          </div>
        </div>
      </div>
    </div>
  );

  return createPortal(body, document.body);
}
