import React, { useEffect, useMemo, useState } from 'react';
import { createPortal } from 'react-dom';
import { useCreateMandatMutation, useCreateAvenantMutation, useGetMeQuery } from '../api/baseApi';

/**
 * ManualDocsWizard
 * Props:
 *  - open: boolean
 *  - onClose: () => void
 *  - proprietaires: array of owners available for selection
 *  - defaultProprietaireId: number | undefined
 *  - defaultDateDebut: string (yyyy-mm-dd, prefilled from UniteOwners)
 *  - defaultDateFin: string (yyyy-mm-dd, prefilled from UniteOwners)
 *  - uniteDescription: string (optional prefilled description)
 *  - allowAvenant: boolean (if user wants to optionally create avenant right after mandat)
 *  - lockCoreFields: boolean (if true, proprietaire and dates are prefilled and disabled)
 */
export default function ManualDocsWizard({ open, onClose, proprietaires, defaultProprietaireId, defaultDateDebut, defaultDateFin, uniteDescription, allowAvenant, lockCoreFields = false }) {
  const { data: me } = useGetMeQuery();
  const [createMandat, { isLoading: isSavingMandat }] = useCreateMandatMutation();
  const [createAvenant, { isLoading: isSavingAvenant }] = useCreateAvenantMutation();
  // step: 0 select mode, 1 mandat form, 2 avenant form, 3 done
  const [step, setStep] = useState(0);
  const [mode, setMode] = useState('both'); // 'mandat' | 'avenant' | 'both'
  const [mandat, setMandat] = useState({
    proprietaire_id: defaultProprietaireId || '',
    date_debut: defaultDateDebut || '',
    date_fin: defaultDateFin || '',
    assiette_honoraires: 'loyers_encaisse',
    taux_gestion_pct: '',
    tva_applicable: false,
    tva_taux: '',
    frais_min_mensuel: '',
    periodicite_releve: 'mensuel',
    charge_maintenance: 'proprietaire',
    mode_versement: 'virement',
    description_bien: uniteDescription || '',
    usage_bien: 'habitation',
    pouvoirs_accordes: '',
    lieu_signature: '',
    date_signature: '',
    langue: 'fr',
    notes_clauses: '',
    statut: 'brouillon',
  });

  const [avenant, setAvenant] = useState({
    mandat_id: null,
    reference: '',
    date_pouvoir_initial: '',
    objet_resume: '',
    modifs_text: '',
    date_effet: '',
    lieu_signature: '',
    date_signature: '',
    rep_b_user_id: undefined,
    fichier_url: '',
    created_by: undefined,
    statut: 'brouillon'
  });

  const [errors, setErrors] = useState({});
  const [avenantErrors, setAvenantErrors] = useState({});
  const [createdMandat, setCreatedMandat] = useState(null);
  const [createdAvenant, setCreatedAvenant] = useState(null);

  useEffect(() => {
    if (me?.id) {
      setAvenant(a => ({ ...a, rep_b_user_id: me.id, created_by: me.id }));
    }
  }, [me]);

  // Keep mandat core fields in sync with owner flow and lock them
  useEffect(() => {
    setMandat(m => ({
      ...m,
      proprietaire_id: defaultProprietaireId || m.proprietaire_id,
      date_debut: defaultDateDebut || m.date_debut,
      date_fin: defaultDateFin || m.date_fin,
    }));
  }, [defaultProprietaireId, defaultDateDebut, defaultDateFin]);

  if (!open) return null;

  const validateMandat = () => {
    const e = {};
    // Seulement le propriétaire est obligatoire, tout le reste est optionnel
    if (!mandat.proprietaire_id) e.proprietaire_id = 'Choisir un propriétaire';
    // Validation dates si elles sont présentes
    if (mandat.date_fin && mandat.date_debut && mandat.date_fin < mandat.date_debut) {
      e.date_fin = 'Date fin doit être >= date début';
    }
    return e;
  };

  const validateAvenant = () => {
    const e = {};
    // Seulement mandat_id obligatoire, tout le reste optionnel
    if (!avenant.mandat_id) e.mandat_id = 'Mandat requis';
    return e;
  };

  const saveMandat = async () => {
    const e = validateMandat();
    setErrors(e);
    if (Object.keys(e).length) return;
    try {
      const payload = {
        ...mandat,
        proprietaire_id: Number(mandat.proprietaire_id),
        taux_gestion_pct: mandat.taux_gestion_pct ? Number(mandat.taux_gestion_pct) : null,
        tva_taux: mandat.tva_taux ? Number(mandat.tva_taux) : null,
        frais_min_mensuel: mandat.frais_min_mensuel ? Number(mandat.frais_min_mensuel) : null,
      };
      // Ensure reference is autogenerated by backend: do not send empty reference
      delete payload.reference;
      const res = await createMandat(payload).unwrap();
      setCreatedMandat(res);
      setAvenant(a => ({ ...a, mandat_id: res.id }));
      if (mode === 'both' && allowAvenant) setStep(2);
      else setStep(3);
    } catch (err) {
      console.error(err);
      alert('Erreur création mandat: ' + (err?.data?.message || err?.message || 'Serveur'));
    }
  };

  const saveAvenant = async () => {
    const e = validateAvenant();
    setAvenantErrors(e);
    if (Object.keys(e).length) return;
    try {
      let payload = {
        ...avenant,
        mandat_id: Number(avenant.mandat_id),
        rep_b_user_id: Number(avenant.rep_b_user_id),
        created_by: avenant.created_by ? Number(avenant.created_by) : undefined
      };
      if (avenant.file) {
        payload.file = avenant.file;
      }
      const res = await createAvenant(payload).unwrap();
      setCreatedAvenant(res);
      setStep(3);
    } catch (err) {
      console.error(err);
      alert('Erreur création avenant: ' + (err?.data?.message || err?.message || 'Serveur'));
    }
  };

  const closeAndReset = () => {
    setStep(0);
    setMode('both');
    setCreatedMandat(null);
    setCreatedAvenant(null);
    setErrors({});
    setAvenantErrors({});
    onClose();
  };

  const chooseStep = (
    <div className="p-4 p-md-5">
      
      
      <div className="row g-3">
        {/* Mandat uniquement */}
        <div className="col-12 col-md-4">
          <div 
            className={`card border-0 shadow-sm h-100 ${mode === 'mandat' ? 'shadow' : ''}`} 
            style={{ 
              cursor: 'pointer',
              background: mode === 'mandat' 
                ? 'linear-gradient(135deg, #dbeafe, #e0e7ff)' 
                : '#ffffff',
              border: mode === 'mandat' ? '2px solid #3b82f6' : '1px solid #e5e7eb',
              transition: 'all 0.3s ease',
              transform: mode === 'mandat' ? 'scale(1.02)' : 'scale(1)'
            }} 
            onClick={() => setMode('mandat')}
            onMouseEnter={(e) => {
              if (mode !== 'mandat') {
                e.currentTarget.style.transform = 'translateY(-4px)';
                e.currentTarget.style.boxShadow = '0 8px 16px rgba(0,0,0,0.12)';
              }
            }}
            onMouseLeave={(e) => {
              if (mode !== 'mandat') {
                e.currentTarget.style.transform = 'translateY(0)';
                e.currentTarget.style.boxShadow = '';
              }
            }}>
            <div className="card-body text-center p-4">
              <div className="form-check d-flex justify-content-center mb-3">
                <input 
                  type="radio" 
                  className="form-check-input" 
                  style={{ width: '24px', height: '24px', cursor: 'pointer' }}
                  name="mode" 
                  checked={mode === 'mandat'} 
                  onChange={() => setMode('mandat')} 
                />
              </div>
              <div className="p-3 rounded-3 d-inline-flex mb-3" style={{ background: 'rgba(59, 130, 246, 0.1)' }}>
                <i className="bi bi-file-text" style={{ fontSize: '2.5rem', color: '#3b82f6' }}></i>
              </div>
              <div className="fw-bold mb-2" style={{ fontSize: '1rem', color: '#1e293b' }}>
                Mandat uniquement
              </div>
              <small className="text-muted d-block">Créer un nouveau mandat de gestion</small>
            </div>
          </div>
        </div>
        
        {/* Avenant uniquement */}
        <div className="col-12 col-md-4">
          <div 
            className={`card border-0 shadow-sm h-100 ${mode === 'avenant' ? 'shadow' : ''}`} 
            style={{ 
              cursor: 'pointer',
              background: mode === 'avenant' 
                ? 'linear-gradient(135deg, #fef3c7, #fde68a)' 
                : '#ffffff',
              border: mode === 'avenant' ? '2px solid #f59e0b' : '1px solid #e5e7eb',
              transition: 'all 0.3s ease',
              transform: mode === 'avenant' ? 'scale(1.02)' : 'scale(1)'
            }} 
            onClick={() => setMode('avenant')}
            onMouseEnter={(e) => {
              if (mode !== 'avenant') {
                e.currentTarget.style.transform = 'translateY(-4px)';
                e.currentTarget.style.boxShadow = '0 8px 16px rgba(0,0,0,0.12)';
              }
            }}
            onMouseLeave={(e) => {
              if (mode !== 'avenant') {
                e.currentTarget.style.transform = 'translateY(0)';
                e.currentTarget.style.boxShadow = '';
              }
            }}>
            <div className="card-body text-center p-4">
              <div className="form-check d-flex justify-content-center mb-3">
                <input 
                  type="radio" 
                  className="form-check-input" 
                  style={{ width: '24px', height: '24px', cursor: 'pointer' }}
                  name="mode" 
                  checked={mode === 'avenant'} 
                  onChange={() => setMode('avenant')} 
                />
              </div>
              <div className="p-3 rounded-3 d-inline-flex mb-3" style={{ background: 'rgba(245, 158, 11, 0.1)' }}>
                <i className="bi bi-file-earmark-plus" style={{ fontSize: '2.5rem', color: '#f59e0b' }}></i>
              </div>
              <div className="fw-bold mb-2" style={{ fontSize: '1rem', color: '#1e293b' }}>
                Avenant uniquement
              </div>
              <small className="text-muted d-block">Créer un avenant pour un mandat existant</small>
            </div>
          </div>
        </div>
        
        {/* Les deux */}
        <div className="col-12 col-md-4">
          <div 
            className={`card border-0 shadow-sm h-100 ${mode === 'both' ? 'shadow' : ''}`} 
            style={{ 
              cursor: 'pointer',
              background: mode === 'both' 
                ? 'linear-gradient(135deg, #d1fae5, #a7f3d0)' 
                : '#ffffff',
              border: mode === 'both' ? '2px solid #10b981' : '1px solid #e5e7eb',
              transition: 'all 0.3s ease',
              transform: mode === 'both' ? 'scale(1.02)' : 'scale(1)'
            }} 
            onClick={() => setMode('both')}
            onMouseEnter={(e) => {
              if (mode !== 'both') {
                e.currentTarget.style.transform = 'translateY(-4px)';
                e.currentTarget.style.boxShadow = '0 8px 16px rgba(0,0,0,0.12)';
              }
            }}
            onMouseLeave={(e) => {
              if (mode !== 'both') {
                e.currentTarget.style.transform = 'translateY(0)';
                e.currentTarget.style.boxShadow = '';
              }
            }}>
            <div className="card-body text-center p-4">
              <div className="form-check d-flex justify-content-center mb-3">
                <input 
                  type="radio" 
                  className="form-check-input" 
                  style={{ width: '24px', height: '24px', cursor: 'pointer' }}
                  name="mode" 
                  checked={mode === 'both'} 
                  onChange={() => setMode('both')} 
                />
              </div>
              <div className="p-3 rounded-3 d-inline-flex mb-3" style={{ background: 'rgba(16, 185, 129, 0.1)' }}>
                <i className="bi bi-files" style={{ fontSize: '2.5rem', color: '#10b981' }}></i>
              </div>
              <div className="fw-bold mb-2" style={{ fontSize: '1rem', color: '#1e293b' }}>
                Les deux
              </div>
              <small className="text-muted d-block">Mandat et avenant en une seule étape</small>
            </div>
          </div>
        </div>
      </div>
      <div className="d-flex justify-content-end mt-4 gap-2">
        <button 
          type="button" 
          className="btn text-white fw-semibold shadow-sm px-4 py-2 d-flex align-items-center gap-2"
          style={{
            background: 'linear-gradient(135deg, #3b82f6, #2563eb)',
            border: 'none',
            borderRadius: '8px',
            transition: 'all 0.3s ease'
          }}
          onClick={() => setStep(mode === 'avenant' ? 2 : 1)}
          onMouseEnter={(e) => {
            e.currentTarget.style.transform = 'translateY(-2px)';
            e.currentTarget.style.boxShadow = '0 8px 20px rgba(59, 130, 246, 0.4)';
          }}
          onMouseLeave={(e) => {
            e.currentTarget.style.transform = 'translateY(0)';
            e.currentTarget.style.boxShadow = '';
          }}>
          Continuer
          <i className="bi bi-arrow-right"></i>
        </button>
      </div>
    </div>
  );

  const mandatForm = (
    <div className="p-4 p-md-5" style={{ background: '#f8fafc' }}>
      <div className="mb-4">
        <div className="d-flex align-items-center gap-3 mb-2">
          <div className="d-inline-flex align-items-center justify-content-center rounded-3" 
               style={{ width: '48px', height: '48px', background: 'linear-gradient(135deg, #3b82f6, #2563eb)' }}>
            <i className="bi bi-file-text" style={{ fontSize: '1.5rem', color: '#ffffff' }}></i>
          </div>
          <div>
            <h5 className="fw-bold mb-1" style={{ color: '#1e293b' }}>Nouveau Mandat de gestion</h5>
            <p className="text-muted mb-0 small">Remplissez les informations du mandat</p>
          </div>
        </div>
      </div>

      {/* Section: Informations principales */}
      <div className="card border-0 shadow-sm mb-4" style={{ borderRadius: '16px' }}>
        <div className="card-body p-4">
          <div className="d-flex align-items-center gap-2 mb-4" 
               style={{ 
                 paddingBottom: '12px', 
                 borderBottom: '2px solid #e0e7ff'
               }}>
            <div className="d-inline-flex align-items-center justify-content-center rounded-circle" 
                 style={{ width: '32px', height: '32px', background: '#dbeafe' }}>
              <i className="bi bi-person-circle" style={{ fontSize: '1rem', color: '#3b82f6' }}></i>
            </div>
            <h6 className="fw-bold mb-0" style={{ color: '#1e293b' }}>Propriétaire et période</h6>
          </div>
        <div className="row g-3">
            <h6 className="fw-bold mb-0" style={{ color: '#1e293b' }}>Propriétaire et période</h6>
          </div>
          <div className="row g-3">
            <div className="col-md-6">
              <label className="form-label fw-semibold mb-2" style={{ color: '#334155', fontSize: '0.9rem' }}>
                Propriétaire <span style={{ color: '#ef4444' }}>*</span>
              </label>
              <select 
                className={`form-select ${errors.proprietaire_id ? 'is-invalid' : ''}`} 
                value={mandat.proprietaire_id} 
                onChange={e => setMandat(m => ({ ...m, proprietaire_id: e.target.value }))} 
                disabled={lockCoreFields && !!mandat.proprietaire_id}
                style={{ 
                  borderColor: errors.proprietaire_id ? '#ef4444' : '#cbd5e1',
                  fontSize: '0.95rem',
                  padding: '0.65rem 0.75rem'
                }}>
                <option value="">Sélectionner un propriétaire...</option>
                {proprietaires.map(p => <option key={p.id} value={p.id}>{p.nom_raison || p.email || `#${p.id}`}</option>)}
              </select>
              {errors.proprietaire_id && <div className="invalid-feedback" style={{ fontSize: '0.85rem' }}>{errors.proprietaire_id}</div>}
              {lockCoreFields && mandat.proprietaire_id && (
                <div className="form-text" style={{ color: '#0ea5e9', fontSize: '0.85rem' }}>
                  <i className="bi bi-lock-fill me-1"></i>Défini par la répartition de l'unité
                </div>
              )}
            </div>
            <div className="col-md-3">
              <label className="form-label fw-semibold mb-2" style={{ color: '#334155', fontSize: '0.9rem' }}>
                Date début
              </label>
              <input 
                type="date" 
                className={`form-control ${errors.date_debut ? 'is-invalid' : ''}`} 
                value={mandat.date_debut} 
                onChange={e => setMandat(m => ({ ...m, date_debut: e.target.value }))} 
                disabled={lockCoreFields}
                style={{ 
                  borderColor: errors.date_debut ? '#ef4444' : '#cbd5e1',
                  fontSize: '0.95rem',
                  padding: '0.65rem 0.75rem'
                }} />
              {errors.date_debut && <div className="invalid-feedback" style={{ fontSize: '0.85rem' }}>{errors.date_debut}</div>}
              {lockCoreFields && (
                <div className="form-text" style={{ color: '#0ea5e9', fontSize: '0.85rem' }}>
                  <i className="bi bi-lock-fill me-1"></i>Défini automatiquement
                </div>
              )}
            </div>
            <div className="col-md-3">
              <label className="form-label fw-semibold mb-2" style={{ color: '#334155', fontSize: '0.9rem' }}>
                Date fin
              </label>
              <input 
                type="date" 
                className={`form-control ${errors.date_fin ? 'is-invalid' : ''}`} 
                value={mandat.date_fin} 
                onChange={e => setMandat(m => ({ ...m, date_fin: e.target.value }))} 
                disabled={lockCoreFields}
                style={{ 
                  borderColor: errors.date_fin ? '#ef4444' : '#cbd5e1',
                  fontSize: '0.95rem',
                  padding: '0.65rem 0.75rem'
                }} />
              {errors.date_fin && <div className="invalid-feedback" style={{ fontSize: '0.85rem' }}>{errors.date_fin}</div>}
              {lockCoreFields && (
                <div className="form-text" style={{ color: '#0ea5e9', fontSize: '0.85rem' }}>
                  <i className="bi bi-lock-fill me-1"></i>Défini automatiquement
                </div>
              )}
            </div>
          </div>
        </div>
      </div>

      {/* Section: Honoraires */}
      <div className="card border-0 shadow-sm mb-4" style={{ borderRadius: '16px' }}>
        <div className="card-body p-4">
          <div className="d-flex align-items-center gap-2 mb-4" 
               style={{ 
                 paddingBottom: '12px', 
                 borderBottom: '2px solid #d1fae5'
               }}>
            <div className="d-inline-flex align-items-center justify-content-center rounded-circle" 
                 style={{ width: '32px', height: '32px', background: '#d1fae5' }}>
              <i className="bi bi-cash-coin" style={{ fontSize: '1rem', color: '#10b981' }}></i>
            </div>
            <h6 className="fw-bold mb-0" style={{ color: '#1e293b' }}>Honoraires et gestion</h6>
          </div>
          <div className="row g-3">
            <div className="col-md-4">
              <label className="form-label fw-semibold mb-2" style={{ color: '#334155', fontSize: '0.9rem' }}>
                Taux de gestion (%)
              </label>
              <div className="input-group">
                <input 
                  type="number" 
                  step="0.01" 
                  className="form-control" 
                  value={mandat.taux_gestion_pct} 
                  onChange={e => setMandat(m => ({ ...m, taux_gestion_pct: e.target.value }))} 
                  placeholder="0.00"
                  style={{ 
                    borderColor: '#cbd5e1',
                    fontSize: '0.95rem',
                    padding: '0.65rem 0.75rem'
                  }} />
                <span className="input-group-text" style={{ background: '#f1f5f9', borderColor: '#cbd5e1', color: '#64748b' }}>%</span>
              </div>
            </div>
            <div className="col-md-4">
              <label className="form-label fw-semibold mb-2" style={{ color: '#334155', fontSize: '0.9rem' }}>
                Langue
              </label>
              <select 
                className="form-select" 
                value={mandat.langue} 
                onChange={e => setMandat(m => ({ ...m, langue: e.target.value }))}
                style={{ 
                  borderColor: '#cbd5e1',
                  fontSize: '0.95rem',
                  padding: '0.65rem 0.75rem'
                }}>
                <option value="fr">🇫🇷 Français</option>
                <option value="ar">🇲🇦 Arabe</option>
                <option value="ar_fr">🇲🇦🇫🇷 Ar + Fr</option>
              </select>
            </div>
            <div className="col-md-4">
              <label className="form-label fw-semibold mb-2" style={{ color: '#334155', fontSize: '0.9rem' }}>
                Statut
              </label>
              <select 
                className="form-select" 
                value={mandat.statut} 
                onChange={e => setMandat(m => ({ ...m, statut: e.target.value }))}
                style={{ 
                  borderColor: '#cbd5e1',
                  fontSize: '0.95rem',
                  padding: '0.65rem 0.75rem'
                }}>
                <option value="brouillon">📝 Brouillon</option>
                <option value="en_validation">⏳ En validation</option>
                <option value="signe">✅ Signé</option>
                <option value="actif">🟢 Actif</option>
                <option value="resilie">🔴 Résilié</option>
              </select>
            </div>
          </div>
        </div>
      </div>

      {/* Section: Description */}
      <div className="card border-0 shadow-sm mb-4" style={{ borderRadius: '16px' }}>
        <div className="card-body p-4">
          <div className="d-flex align-items-center gap-2 mb-4" 
               style={{ 
                 paddingBottom: '12px', 
                 borderBottom: '2px solid #fef3c7'
               }}>
            <div className="d-inline-flex align-items-center justify-content-center rounded-circle" 
                 style={{ width: '32px', height: '32px', background: '#fef3c7' }}>
              <i className="bi bi-file-earmark-text" style={{ fontSize: '1rem', color: '#f59e0b' }}></i>
            </div>
            <h6 className="fw-bold mb-0" style={{ color: '#1e293b' }}>Description et clauses</h6>
          </div>
          <div className="row g-3">
            <div className="col-12">
              <label className="form-label fw-semibold mb-2" style={{ color: '#334155', fontSize: '0.9rem' }}>
                Description du bien
              </label>
              <textarea 
                className="form-control" 
                rows={2} 
                value={mandat.description_bien} 
                onChange={e => setMandat(m => ({ ...m, description_bien: e.target.value }))} 
                placeholder="Décrire le bien géré..."
                style={{ 
                  borderColor: '#cbd5e1',
                  fontSize: '0.95rem',
                  padding: '0.75rem'
                }} />
            </div>
            <div className="col-12">
              <label className="form-label fw-semibold mb-2" style={{ color: '#334155', fontSize: '0.9rem' }}>
                Pouvoirs accordés / Texte
              </label>
              <textarea 
                className="form-control" 
                rows={3} 
                value={mandat.pouvoirs_accordes} 
                onChange={e => setMandat(m => ({ ...m, pouvoirs_accordes: e.target.value }))} 
                placeholder="Détailler les pouvoirs accordés au gestionnaire..."
                style={{ 
                  borderColor: '#cbd5e1',
                  fontSize: '0.95rem',
                  padding: '0.75rem'
                }} />
            </div>
            <div className="col-12">
              <label className="form-label fw-semibold mb-2" style={{ color: '#334155', fontSize: '0.9rem' }}>
                Clauses / Notes additionnelles
              </label>
              <textarea 
                className="form-control" 
                rows={2} 
                value={mandat.notes_clauses} 
                onChange={e => setMandat(m => ({ ...m, notes_clauses: e.target.value }))} 
                placeholder="Notes ou clauses particulières..."
                style={{ 
                  borderColor: '#cbd5e1',
                  fontSize: '0.95rem',
                  padding: '0.75rem'
                }} />
            </div>
          </div>
        </div>
      </div>

      {/* Section: Signature */}
      <div className="card border-0 shadow-sm mb-4" style={{ borderRadius: '16px' }}>
        <div className="card-body p-4">
          <div className="d-flex align-items-center gap-2 mb-4" 
               style={{ 
                 paddingBottom: '12px', 
                 borderBottom: '2px solid #e9d5ff'
               }}>
            <div className="d-inline-flex align-items-center justify-content-center rounded-circle" 
                 style={{ width: '32px', height: '32px', background: '#e9d5ff' }}>
              <i className="bi bi-pen" style={{ fontSize: '1rem', color: '#a855f7' }}></i>
            </div>
            <h6 className="fw-bold mb-0" style={{ color: '#1e293b' }}>Signature</h6>
          </div>
          <div className="row g-3">
            <div className="col-md-4">
              <label className="form-label fw-semibold mb-2" style={{ color: '#334155', fontSize: '0.9rem' }}>
                Date de signature
              </label>
              <input 
                type="date" 
                className="form-control" 
                value={mandat.date_signature} 
                onChange={e => setMandat(m => ({ ...m, date_signature: e.target.value }))}
                style={{ 
                  borderColor: '#cbd5e1',
                  fontSize: '0.95rem',
                  padding: '0.65rem 0.75rem'
                }} />
            </div>
            <div className="col-md-4">
              <label className="form-label fw-semibold mb-2" style={{ color: '#334155', fontSize: '0.9rem' }}>
                Lieu de signature
              </label>
              <input 
                type="text" 
                className="form-control" 
                value={mandat.lieu_signature} 
                onChange={e => setMandat(m => ({ ...m, lieu_signature: e.target.value }))} 
                placeholder="Ville ou lieu..."
                style={{ 
                  borderColor: '#cbd5e1',
                  fontSize: '0.95rem',
                  padding: '0.65rem 0.75rem'
                }} />
            </div>
            <div className="col-md-4">
              <label className="form-label fw-semibold mb-2" style={{ color: '#334155', fontSize: '0.9rem' }}>
                Fichier URL (optionnel)
              </label>
              <input 
                type="text" 
                className="form-control" 
                value={mandat.fichier_url} 
                onChange={e => setMandat(m => ({ ...m, fichier_url: e.target.value }))} 
                placeholder="https://..."
                style={{ 
                  borderColor: '#cbd5e1',
                  fontSize: '0.95rem',
                  padding: '0.65rem 0.75rem'
                }} />
            </div>
          </div>
        </div>
      </div>

      <div className="d-flex justify-content-between mt-4 gap-3">
        <button 
          type="button" 
          className="btn px-4 d-flex align-items-center gap-2" 
          disabled={isSavingMandat} 
          onClick={() => setStep(0)}
          style={{
            background: '#ffffff',
            border: '2px solid #e2e8f0',
            color: '#64748b',
            borderRadius: '8px',
            fontWeight: '600',
            padding: '0.5rem 1.25rem'
          }}
          onMouseEnter={(e) => {
            e.currentTarget.style.background = '#f8fafc';
            e.currentTarget.style.borderColor = '#cbd5e1';
          }}
          onMouseLeave={(e) => {
            e.currentTarget.style.background = '#ffffff';
            e.currentTarget.style.borderColor = '#e2e8f0';
          }}>
          <i className="bi bi-arrow-left"></i>
          Précédent
        </button>
        <button 
          type="button" 
          className="btn px-4 d-flex align-items-center gap-2" 
          disabled={isSavingMandat} 
          onClick={saveMandat}
          style={{
            background: 'linear-gradient(135deg, #3b82f6, #2563eb)',
            border: 'none',
            color: '#ffffff',
            borderRadius: '8px',
            fontWeight: '600',
            padding: '0.5rem 1.25rem',
            boxShadow: '0 4px 12px rgba(59, 130, 246, 0.3)'
          }}
          onMouseEnter={(e) => {
            e.currentTarget.style.transform = 'translateY(-2px)';
            e.currentTarget.style.boxShadow = '0 8px 20px rgba(59, 130, 246, 0.4)';
          }}
          onMouseLeave={(e) => {
            e.currentTarget.style.transform = 'translateY(0)';
            e.currentTarget.style.boxShadow = '0 4px 12px rgba(59, 130, 246, 0.3)';
          }}>
          {isSavingMandat ? (
            <>
              <span className="spinner-border spinner-border-sm"></span>
              Création en cours...
            </>
          ) : (
            <>
              <i className="bi bi-check-circle"></i>
              Créer le mandat
            </>
          )}
        </button>
      </div>
    </div>
  );

  const avenantForm = (
    <div className="p-4 p-md-5" style={{ background: '#f8fafc' }}>
      <div className="mb-4">
        <div className="d-flex align-items-center gap-3 mb-2">
          <div className="d-inline-flex align-items-center justify-content-center rounded-3" 
               style={{ width: '48px', height: '48px', background: 'linear-gradient(135deg, #f59e0b, #d97706)' }}>
            <i className="bi bi-file-earmark-plus" style={{ fontSize: '1.5rem', color: '#ffffff' }}></i>
          </div>
          <div>
            <h5 className="fw-bold mb-1" style={{ color: '#1e293b' }}>Nouvel Avenant</h5>
            <p className="text-muted mb-0 small">Remplissez les informations de l'avenant</p>
          </div>
        </div>
      </div>

      {/* Section: Identification */}
      <div className="card border-0 shadow-sm mb-4" style={{ borderRadius: '16px' }}>
        <div className="card-body p-4">
          <div className="d-flex align-items-center gap-2 mb-4" 
               style={{ 
                 paddingBottom: '12px', 
                 borderBottom: '2px solid #e0e7ff'
               }}>
            <div className="d-inline-flex align-items-center justify-content-center rounded-circle" 
                 style={{ width: '32px', height: '32px', background: '#dbeafe' }}>
              <i className="bi bi-hash" style={{ fontSize: '1rem', color: '#3b82f6' }}></i>
            </div>
            <h6 className="fw-bold mb-0" style={{ color: '#1e293b' }}>Identification</h6>
          </div>
          <div className="row g-3">
            {!createdMandat && (
              <div className="col-md-4">
                <label className="form-label fw-semibold mb-2" style={{ color: '#334155', fontSize: '0.9rem' }}>
                  ID Mandat <span style={{ color: '#ef4444' }}>*</span>
                </label>
                <input 
                  type="number" 
                  className={`form-control ${avenantErrors.mandat_id ? 'is-invalid' : ''}`} 
                  value={avenant.mandat_id || ''} 
                  onChange={e => setAvenant(a => ({ ...a, mandat_id: e.target.value }))} 
                  placeholder="Ex: 123"
                  style={{ 
                    borderColor: avenantErrors.mandat_id ? '#ef4444' : '#cbd5e1',
                    fontSize: '0.95rem',
                    padding: '0.65rem 0.75rem'
                  }} />
                {avenantErrors.mandat_id && <div className="invalid-feedback" style={{ fontSize: '0.85rem' }}>{avenantErrors.mandat_id}</div>}
              </div>
            )}
            <div className="col-md-4">
              <label className="form-label fw-semibold mb-2" style={{ color: '#334155', fontSize: '0.9rem' }}>
                Référence
              </label>
              <input 
                type="text" 
                className="form-control" 
                value={avenant.reference} 
                onChange={e => setAvenant(a => ({ ...a, reference: e.target.value }))} 
                placeholder="AV-2024-..."
                style={{ 
                  borderColor: '#cbd5e1',
                  fontSize: '0.95rem',
                  padding: '0.65rem 0.75rem'
                }} />
            </div>
            <div className="col-md-4">
              <label className="form-label fw-semibold mb-2" style={{ color: '#334155', fontSize: '0.9rem' }}>
                Statut
              </label>
              <select 
                className="form-select" 
                value={avenant.statut} 
                onChange={e => setAvenant(a => ({ ...a, statut: e.target.value }))}
                style={{ 
                  borderColor: '#cbd5e1',
                  fontSize: '0.95rem',
                  padding: '0.65rem 0.75rem'
                }}>
                <option value="brouillon">📝 Brouillon</option>
                <option value="signe">✅ Signé</option>
                <option value="actif">🟢 Actif</option>
                <option value="annule">🔴 Annulé</option>
              </select>
            </div>
          </div>
        </div>
      </div>

      {/* Section: Dates et objet */}
      <div className="card border-0 shadow-sm mb-4" style={{ borderRadius: '16px' }}>
        <div className="card-body p-4">
          <div className="d-flex align-items-center gap-2 mb-4" 
               style={{ 
                 paddingBottom: '12px', 
                 borderBottom: '2px solid #d1fae5'
               }}>
            <div className="d-inline-flex align-items-center justify-content-center rounded-circle" 
                 style={{ width: '32px', height: '32px', background: '#d1fae5' }}>
              <i className="bi bi-calendar-range" style={{ fontSize: '1rem', color: '#10b981' }}></i>
            </div>
            <h6 className="fw-bold mb-0" style={{ color: '#1e293b' }}>Dates et objet</h6>
          </div>
          <div className="row g-3">
            <div className="col-md-4">
              <label className="form-label fw-semibold mb-2" style={{ color: '#334155', fontSize: '0.9rem' }}>
                Date pouvoir initial
              </label>
              <input 
                type="date" 
                className="form-control" 
                value={avenant.date_pouvoir_initial || ''} 
                onChange={e => setAvenant(a => ({ ...a, date_pouvoir_initial: e.target.value }))}
                style={{ 
                  borderColor: '#cbd5e1',
                  fontSize: '0.95rem',
                  padding: '0.65rem 0.75rem'
                }} />
            </div>
            <div className="col-md-4">
              <label className="form-label fw-semibold mb-2" style={{ color: '#334155', fontSize: '0.9rem' }}>
                Date d'effet
              </label>
              <input 
                type="date" 
                className={`form-control ${avenantErrors.date_effet ? 'is-invalid' : ''}`} 
                value={avenant.date_effet} 
                onChange={e => setAvenant(a => ({ ...a, date_effet: e.target.value }))}
                style={{ 
                  borderColor: avenantErrors.date_effet ? '#ef4444' : '#cbd5e1',
                  fontSize: '0.95rem',
                  padding: '0.65rem 0.75rem'
                }} />
              {avenantErrors.date_effet && <div className="invalid-feedback" style={{ fontSize: '0.85rem' }}>{avenantErrors.date_effet}</div>}
            </div>
            <div className="col-md-4">
              <label className="form-label fw-semibold mb-2" style={{ color: '#334155', fontSize: '0.9rem' }}>
                Date de signature
              </label>
              <input 
                type="date" 
                className="form-control" 
                value={avenant.date_signature || ''} 
                onChange={e => setAvenant(a => ({ ...a, date_signature: e.target.value }))}
                style={{ 
                  borderColor: '#cbd5e1',
                  fontSize: '0.95rem',
                  padding: '0.65rem 0.75rem'
                }} />
            </div>
            <div className="col-12">
              <label className="form-label fw-semibold mb-2" style={{ color: '#334155', fontSize: '0.9rem' }}>
                Objet / Résumé
              </label>
              <input 
                type="text" 
                className="form-control" 
                value={avenant.objet_resume} 
                onChange={e => setAvenant(a => ({ ...a, objet_resume: e.target.value }))} 
                placeholder="Bref résumé de l'objet de l'avenant..."
                style={{ 
                  borderColor: '#cbd5e1',
                  fontSize: '0.95rem',
                  padding: '0.65rem 0.75rem'
                }} />
            </div>
          </div>
        </div>
      </div>

      {/* Section: Modifications */}
      <div className="card border-0 shadow-sm mb-4" style={{ borderRadius: '16px' }}>
        <div className="card-body p-4">
          <div className="d-flex align-items-center gap-2 mb-4" 
               style={{ 
                 paddingBottom: '12px', 
                 borderBottom: '2px solid #fef3c7'
               }}>
            <div className="d-inline-flex align-items-center justify-content-center rounded-circle" 
                 style={{ width: '32px', height: '32px', background: '#fef3c7' }}>
              <i className="bi bi-pencil-square" style={{ fontSize: '1rem', color: '#f59e0b' }}></i>
            </div>
            <h6 className="fw-bold mb-0" style={{ color: '#1e293b' }}>Modifications et texte</h6>
          </div>
          <div className="row g-3">
            <div className="col-12">
              <label className="form-label fw-semibold mb-2" style={{ color: '#334155', fontSize: '0.9rem' }}>
                Modifications / Texte détaillé
              </label>
              <textarea 
                className="form-control" 
                rows={4} 
                value={avenant.modifs_text} 
                onChange={e => setAvenant(a => ({ ...a, modifs_text: e.target.value }))} 
                placeholder="Détailler les modifications apportées par cet avenant..."
                style={{ 
                  borderColor: '#cbd5e1',
                  fontSize: '0.95rem',
                  padding: '0.75rem'
                }} />
            </div>
          </div>
        </div>
      </div>

      {/* Section: Signature et fichier */}
      <div className="card border-0 shadow-sm mb-4" style={{ borderRadius: '16px' }}>
        <div className="card-body p-4">
          <div className="d-flex align-items-center gap-2 mb-4" 
               style={{ 
                 paddingBottom: '12px', 
                 borderBottom: '2px solid #e9d5ff'
               }}>
            <div className="d-inline-flex align-items-center justify-content-center rounded-circle" 
                 style={{ width: '32px', height: '32px', background: '#e9d5ff' }}>
              <i className="bi bi-pen" style={{ fontSize: '1rem', color: '#a855f7' }}></i>
            </div>
            <h6 className="fw-bold mb-0" style={{ color: '#1e293b' }}>Signature et fichier</h6>
          </div>
          <div className="row g-3">
            <div className="col-md-4">
              <label className="form-label fw-semibold mb-2" style={{ color: '#334155', fontSize: '0.9rem' }}>
                Lieu de signature
              </label>
              <input 
                type="text" 
                className="form-control" 
                value={avenant.lieu_signature} 
                onChange={e => setAvenant(a => ({ ...a, lieu_signature: e.target.value }))} 
                placeholder="Ville ou lieu..."
                style={{ 
                  borderColor: '#cbd5e1',
                  fontSize: '0.95rem',
                  padding: '0.65rem 0.75rem'
                }} />
            </div>
            <div className="col-md-4">
              <label className="form-label fw-semibold mb-2" style={{ color: '#334155', fontSize: '0.9rem' }}>
                Signataire interne (ID)
              </label>
              <input 
                type="number" 
                className={`form-control ${avenantErrors.rep_b_user_id ? 'is-invalid' : ''}`} 
                value={avenant.rep_b_user_id || ''} 
                onChange={e => setAvenant(a => ({ ...a, rep_b_user_id: e.target.value }))} 
                placeholder="ID utilisateur"
                style={{ 
                  borderColor: avenantErrors.rep_b_user_id ? '#ef4444' : '#cbd5e1',
                  fontSize: '0.95rem',
                  padding: '0.65rem 0.75rem'
                }} />
              {avenantErrors.rep_b_user_id && <div className="invalid-feedback" style={{ fontSize: '0.85rem' }}>{avenantErrors.rep_b_user_id}</div>}
            </div>
            <div className="col-md-4">
              <label className="form-label fw-semibold mb-2" style={{ color: '#334155', fontSize: '0.9rem' }}>
                Créé par (ID)
              </label>
              <input 
                type="number" 
                className="form-control" 
                value={avenant.created_by || ''} 
                onChange={e => setAvenant(a => ({ ...a, created_by: e.target.value }))} 
                placeholder={`Par défaut: ${me?.id ?? '...'}`}
                style={{ 
                  borderColor: '#cbd5e1',
                  fontSize: '0.95rem',
                  padding: '0.65rem 0.75rem'
                }} />
              <div className="form-text" style={{ fontSize: '0.85rem', color: '#64748b' }}>
                Par défaut: votre ID ({me?.id ?? '...'})
              </div>
            </div>
            <div className="col-12">
              <label className="form-label fw-semibold mb-2" style={{ color: '#334155', fontSize: '0.9rem' }}>
                Fichier (upload)
              </label>
              <input 
                type="file" 
                className="form-control" 
                accept=".pdf,.jpg,.jpeg,.png" 
                onChange={e => {
                  const file = e.target.files?.[0];
                  setAvenant(a => ({ ...a, file }));
                }}
                style={{ 
                  borderColor: '#cbd5e1',
                  fontSize: '0.95rem',
                  padding: '0.65rem 0.75rem'
                }} />
              {avenant.fichier_url && (
                <div className="alert alert-info mt-2 mb-0 py-2 px-3 d-flex align-items-center gap-2" 
                     style={{ 
                       background: '#dbeafe', 
                       border: '1px solid #93c5fd',
                       borderRadius: '8px',
                       fontSize: '0.9rem'
                     }}>
                  <i className="bi bi-file-earmark-check" style={{ color: '#3b82f6' }}></i>
                  <span style={{ color: '#1e40af' }}>Fichier actuel: <a href={avenant.fichier_url} target="_blank" rel="noreferrer" className="alert-link fw-semibold">ouvrir</a></span>
                </div>
              )}
            </div>
          </div>
        </div>
      </div>

      <div className="d-flex justify-content-between mt-4 gap-3">
        <button 
          type="button" 
          className="btn px-4 d-flex align-items-center gap-2" 
          disabled={isSavingAvenant} 
          onClick={() => setStep(mode === 'both' && createdMandat ? 3 : 0)}
          style={{
            background: '#ffffff',
            border: '2px solid #e2e8f0',
            color: '#64748b',
            borderRadius: '8px',
            fontWeight: '600',
            padding: '0.5rem 1.25rem'
          }}
          onMouseEnter={(e) => {
            e.currentTarget.style.background = '#f8fafc';
            e.currentTarget.style.borderColor = '#cbd5e1';
          }}
          onMouseLeave={(e) => {
            e.currentTarget.style.background = '#ffffff';
            e.currentTarget.style.borderColor = '#e2e8f0';
          }}>
          <i className="bi bi-arrow-left"></i>
          Précédent
        </button>
        <button 
          type="button" 
          className="btn px-4 d-flex align-items-center gap-2" 
          disabled={isSavingAvenant} 
          onClick={saveAvenant}
          style={{
            background: 'linear-gradient(135deg, #f59e0b, #d97706)',
            border: 'none',
            color: '#ffffff',
            borderRadius: '8px',
            fontWeight: '600',
            padding: '0.5rem 1.25rem',
            boxShadow: '0 4px 12px rgba(245, 158, 11, 0.3)'
          }}
          onMouseEnter={(e) => {
            e.currentTarget.style.transform = 'translateY(-2px)';
            e.currentTarget.style.boxShadow = '0 8px 20px rgba(245, 158, 11, 0.4)';
          }}
          onMouseLeave={(e) => {
            e.currentTarget.style.transform = 'translateY(0)';
            e.currentTarget.style.boxShadow = '0 4px 12px rgba(245, 158, 11, 0.3)';
          }}>
          {isSavingAvenant ? (
            <>
              <span className="spinner-border spinner-border-sm"></span>
              Création en cours...
            </>
          ) : (
            <>
              <i className="bi bi-check-circle"></i>
              Créer l'avenant
            </>
          )}
        </button>
      </div>
    </div>
  );

  const doneView = (
    <div className="text-center py-5 px-4">
      <div className="mb-4">
        <div className="d-inline-flex align-items-center justify-content-center rounded-circle mb-3" 
             style={{
               width: '100px',
               height: '100px',
               background: 'linear-gradient(135deg, #d1fae5, #a7f3d0)'
             }}>
          <i className="bi bi-check-circle-fill" style={{ fontSize: '3.5rem', color: '#10b981' }}></i>
        </div>
        <h4 className="fw-bold mb-2" style={{ color: '#1e293b' }}>Création terminée avec succès !</h4>
        <p className="text-muted mb-0">Vos documents ont été créés et enregistrés</p>
      </div>
      <div className="mb-5 d-flex flex-column align-items-center gap-3">
        {createdMandat && (
          <div className="alert alert-success border-0 shadow-sm d-inline-flex align-items-center px-4 py-3 mb-0" 
               style={{ 
                 background: 'linear-gradient(135deg, #dbeafe, #e0e7ff)',
                 borderRadius: '12px',
                 minWidth: '300px'
               }}>
            <div className="p-2 rounded-circle me-3" style={{ background: 'rgba(59, 130, 246, 0.2)' }}>
              <i className="bi bi-file-text" style={{ fontSize: '1.5rem', color: '#3b82f6' }}></i>
            </div>
            <div className="text-start">
              <div className="fw-bold" style={{ color: '#1e293b' }}>Mandat de gestion</div>
              <small className="text-muted">Document #{createdMandat.id} créé</small>
            </div>
          </div>
        )}
        {createdAvenant && (
          <div className="alert alert-info border-0 shadow-sm d-inline-flex align-items-center px-4 py-3 mb-0"
               style={{ 
                 background: 'linear-gradient(135deg, #fef3c7, #fde68a)',
                 borderRadius: '12px',
                 minWidth: '300px'
               }}>
            <div className="p-2 rounded-circle me-3" style={{ background: 'rgba(245, 158, 11, 0.2)' }}>
              <i className="bi bi-file-earmark-plus" style={{ fontSize: '1.5rem', color: '#f59e0b' }}></i>
            </div>
            <div className="text-start">
              <div className="fw-bold" style={{ color: '#1e293b' }}>Avenant au mandat</div>
              <small className="text-muted">Document #{createdAvenant.id} créé</small>
            </div>
          </div>
        )}
      </div>
      <div className="d-flex justify-content-center gap-2">
        <button 
          type="button" 
          className="btn text-white fw-semibold shadow-sm px-4 py-2 d-flex align-items-center gap-2"
          style={{
            background: 'linear-gradient(135deg, #10b981, #059669)',
            border: 'none',
            borderRadius: '8px',
            transition: 'all 0.3s ease'
          }}
          onClick={closeAndReset}
          onMouseEnter={(e) => {
            e.currentTarget.style.transform = 'translateY(-2px)';
            e.currentTarget.style.boxShadow = '0 8px 20px rgba(16, 185, 129, 0.4)';
          }}
          onMouseLeave={(e) => {
            e.currentTarget.style.transform = 'translateY(0)';
            e.currentTarget.style.boxShadow = '';
          }}>
          <i className="bi bi-check-lg"></i>
          Terminer
        </button>
      </div>
    </div>
  );

  const body = (
    <div className="modal fade show" style={{ display: 'block', background: 'rgba(15, 23, 42, 0.6)', backdropFilter: 'blur(4px)', zIndex: 1050 }}>
      <div className="modal-dialog modal-xl modal-dialog-centered" style={{ maxWidth: '70vw' }}>
        <div className="modal-content border-0" 
             style={{ 
               borderRadius: '24px',
               overflow: 'hidden',
               boxShadow: '0 25px 50px -12px rgba(0, 0, 0, 0.25)',
               maxHeight: '90vh'
             }}>
          <div className="modal-header border-0" 
               style={{
                 background: 'linear-gradient(135deg, #f8fafc, #f1f5f9)',
                 padding: '2rem 2rem 1.5rem 2rem'
               }}>
            <div className="w-100">
              {/* Progress indicator */}
              <div className="d-flex align-items-center justify-content-between mb-4">
                <div className="d-flex align-items-center gap-2 flex-grow-1">
                  {/* Step 1 */}
                  <div className="d-flex align-items-center gap-2">
                    <div className={`rounded-circle d-flex align-items-center justify-content-center ${step >= 0 ? '' : ''}`} 
                         style={{ 
                           width: '44px', 
                           height: '44px',
                           background: step >= 0 ? 'linear-gradient(135deg, #3b82f6, #2563eb)' : '#e5e7eb',
                           color: step >= 0 ? '#ffffff' : '#9ca3af',
                           fontSize: '16px', 
                           fontWeight: 'bold',
                           boxShadow: step >= 0 ? '0 4px 12px rgba(59, 130, 246, 0.3)' : 'none',
                           transition: 'all 0.3s ease'
                         }}>
                      {step > 0 ? <i className="bi bi-check-lg"></i> : '1'}
                    </div>
                    <div className="d-none d-md-block">
                      <div className={`small ${step >= 0 ? 'fw-bold' : 'text-muted'}`} 
                           style={{ color: step >= 0 ? '#1e293b' : '#9ca3af', fontSize: '0.75rem' }}>
                        Étape 1
                      </div>
                      <div className={`small ${step >= 0 ? 'text-primary fw-semibold' : 'text-muted'}`} 
                           style={{ fontSize: '0.85rem' }}>
                        Type
                      </div>
                    </div>
                  </div>
                  
                  {/* Connector */}
                  <div className="flex-grow-1 mx-2" 
                       style={{ 
                         height: '3px',
                         background: step >= 1 
                           ? 'linear-gradient(90deg, #3b82f6, #2563eb)' 
                           : '#e5e7eb',
                         borderRadius: '2px',
                         minWidth: '30px',
                         maxWidth: '100px',
                         transition: 'all 0.3s ease'
                       }}></div>
                  
                  {/* Step 2 */}
                  <div className="d-flex align-items-center gap-2">
                    <div className={`rounded-circle d-flex align-items-center justify-content-center`} 
                         style={{ 
                           width: '44px', 
                           height: '44px',
                           background: step >= 1 ? 'linear-gradient(135deg, #3b82f6, #2563eb)' : '#e5e7eb',
                           color: step >= 1 ? '#ffffff' : '#9ca3af',
                           fontSize: '16px', 
                           fontWeight: 'bold',
                           boxShadow: step >= 1 ? '0 4px 12px rgba(59, 130, 246, 0.3)' : 'none',
                           transition: 'all 0.3s ease'
                         }}>
                      {step > 1 ? <i className="bi bi-check-lg"></i> : '2'}
                    </div>
                    <div className="d-none d-md-block">
                      <div className={`small ${step >= 1 ? 'fw-bold' : 'text-muted'}`} 
                           style={{ color: step >= 1 ? '#1e293b' : '#9ca3af', fontSize: '0.75rem' }}>
                        Étape 2
                      </div>
                      <div className={`small ${step >= 1 ? 'text-primary fw-semibold' : 'text-muted'}`} 
                           style={{ fontSize: '0.85rem' }}>
                        Informations
                      </div>
                    </div>
                  </div>
                  
                  {/* Connector */}
                  <div className="flex-grow-1 mx-2" 
                       style={{ 
                         height: '3px',
                         background: step >= 3 
                           ? 'linear-gradient(90deg, #10b981, #059669)' 
                           : '#e5e7eb',
                         borderRadius: '2px',
                         minWidth: '30px',
                         maxWidth: '100px',
                         transition: 'all 0.3s ease'
                       }}></div>
                  
                  {/* Step 3 */}
                  <div className="d-flex align-items-center gap-2">
                    <div className={`rounded-circle d-flex align-items-center justify-content-center`} 
                         style={{ 
                           width: '44px', 
                           height: '44px',
                           background: step >= 3 
                             ? 'linear-gradient(135deg, #10b981, #059669)' 
                             : '#e5e7eb',
                           color: step >= 3 ? '#ffffff' : '#9ca3af',
                           fontSize: '16px', 
                           fontWeight: 'bold',
                           boxShadow: step >= 3 ? '0 4px 12px rgba(16, 185, 129, 0.3)' : 'none',
                           transition: 'all 0.3s ease'
                         }}>
                      {step >= 3 ? <i className="bi bi-check-lg"></i> : '3'}
                    </div>
                    <div className="d-none d-md-block">
                      <div className={`small ${step >= 3 ? 'fw-bold' : 'text-muted'}`} 
                           style={{ color: step >= 3 ? '#1e293b' : '#9ca3af', fontSize: '0.75rem' }}>
                        Étape 3
                      </div>
                      <div className={`small ${step >= 3 ? 'text-success fw-semibold' : 'text-muted'}`} 
                           style={{ fontSize: '0.85rem' }}>
                        Terminé
                      </div>
                    </div>
                  </div>
                </div>
                
                <button 
                  type="button" 
                  className="btn-close ms-3" 
                  onClick={closeAndReset}
                  style={{
                    padding: '0.75rem',
                    opacity: 0.6
                  }}
                  onMouseEnter={(e) => e.currentTarget.style.opacity = 1}
                  onMouseLeave={(e) => e.currentTarget.style.opacity = 0.6} />
              </div>
              <h4 className="modal-title fw-bold mb-0" style={{ color: '#1e293b' }}>
                {step === 0 && 'Assistant de création de documents'}
                {step === 1 && 'Mandat de gestion'}
                {step === 2 && 'Avenant au mandat'}
                {step === 3 && 'Finalisation'}
              </h4>
            </div>
          </div>
          <div className="modal-body p-0" style={{ background: '#ffffff', overflowY: step === 0 ? 'visible' : 'auto', maxHeight: step === 0 ? 'none' : 'calc(90vh - 180px)' }}>
            {step === 0 && chooseStep}
            {step === 1 && mandatForm}
            {step === 2 && avenantForm}
            {step === 3 && doneView}
          </div>
        </div>
      </div>
    </div>
  );

  return createPortal(body, document.body);
}
